on:
  pull_request:
    types: edited

jobs:
  pr_body_edited_job:
    runs-on: ubuntu-latest
    if: |
      github.event.changes.body &&
      contains(github.event.pull_request.labels.*.name, 'version-update")
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print new contents
        run: |
          echo "New pull request body: ${{ github.event.pull_request.body }}"