on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: ''
jobs:
  updateVersionFile:
    runs-on: [ubuntu-latest]
    steps:
      - name: Output dir
        run: ls
      - name: Update File
        run: java -Dfile.encoding=UTF-8 -jar modpackUpdater.jar
        env: 
          VERSION: ${{ inputs.version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5